apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ${BUILDCONFIG_NAME}
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ${BUILDCONFIG_NAME}
spec:
  source:
    type: Git
    git:
      uri: ${GIT_URI}
      ref: ${BRANCH_NAME}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: ${IMAGE_STREAM_TAG}
  resources:
    limits:
      memory: 4Gi
      cpu: "2"
    requests:
      memory: 2Gi
      cpu: "1"
  triggers: []
